apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jv67fotbt-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fad2e41b0c.kwy0.p3.openshiftapps.com/rhtap/rhtap-qe:e032dce38b5c4841dce48cfc38674b5628872f3b@sha256:3babcf7aa4c18bbb9915e5ea282413fdb50772c190e944e6954baf77493afcd9
          name: container-image
